"""lol

Revision ID: 693073e82631
Revises: b0f728b89668
Create Date: 2022-04-11 17:17:10.743202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '693073e82631'
down_revision = 'b0f728b89668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('wallet_public', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('wallet_secret', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'wallet_secret')
    op.drop_column('user', 'wallet_public')
    # ### end Alembic commands ###
