"""init

Revision ID: 8a21e1f15bd0
Revises: 
Create Date: 2022-03-27 14:17:53.842392

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a21e1f15bd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lottery')
    op.add_column('item', sa.Column('contract_address', sa.String(length=256), nullable=False))
    op.add_column('user', sa.Column('email', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('phone_country_code', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('phone_number', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'phone_country_code')
    op.drop_column('user', 'email')
    op.drop_column('item', 'contract_address')
    op.create_table('lottery',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.Column('date_modified', mysql.DATETIME(), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('contract_address', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('lottery_type', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('ended', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
